language: groovy
before_script:
- export TERM=dump
- sudo apt-get install cabal-install
- cabal update
- export PATH="$PATH:$HOME/.cabal/bin"
- cabal install alex happy
- cabal install pandoc
- pandoc --version
script:
- export TERM=dumb
- gradle createTemplatesFromGoldenMaster
- gradle arc42
- gradle createDistribution
after_script: "ls -ltra"
install: ''
 
jdk:
- openjdk7
env:
  global:
